name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: Git Checkout
      - name: Run Gradle
        run: ./gradlew check
        working-directory: ./chicken_of_propra