name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Git Checkout
      - name: Run Gradle
        run: ./chicken_of_propra/gradlew -p ./chicken_of_propra check
